name: Main Branch CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Lint and Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Packages
        run: npm i

      - name: Lint Fix
        run: npm run lint:fix

      - name: Prettier Fix
        run: npm run format

      - name: Run Tests
        run: npm run test

      - name: Create Test Coverage Report
        run: npm run coverage

      - name: Webpack Build
        run: npm run build
